// <auto-generated />
using ECommerceStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceStore.Migrations.WarehouseDb
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20180715062448_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerceStore.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductCategory");

                    b.Property<int>("Quantity");

                    b.Property<string>("SKU");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new { ID = 1, Description = "Life-size, role-play accessory features a spring-loaded, retractable blade with switchblade-style action", Image = "https://store.ubi.com/on/demandware.static/-/Sites-masterCatalog/default/dw0e43b641/images/large/57fe647529e1238f668b4568-collectible-2.png", Name = "Assassin's Creed Skull Buckle", Price = 19.54m, ProductCategory = 3, Quantity = 50, SKU = "naab001Knif" },
                        new { ID = 2, Description = "Nothing beats ice cold beer! But if that’s not enough for you, then you could go one step higher–and several degrees lower–with the Frozen Beer Slushy Maker. ", Image = "https://cdn.thisiswhyimbroke.com/images/beer-slushie-machine-300x250.jpg", Name = "Beer Slushie Machine", Price = 53.14m, ProductCategory = 0, Quantity = 50, SKU = "naab002beer" },
                        new { ID = 3, Description = "150ml decanter to hold your favorite liquire or mouthwas - whisky, scotch, bourbon, cognac, brandy all your spirits will look fantastic", Image = "https://i.pinimg.com/originals/20/cf/b2/20cfb20ee822bd1a6a9ccf132ba9cd53.jpg", Name = "Ship In A Bottle Whiskey Dispenser", Price = 120.00m, ProductCategory = 3, Quantity = 50, SKU = "naab003shipdispenser" },
                        new { ID = 4, Description = "A template for shaving or trimming the neckline. The EdgUp guards the back of your hairline so that you can trim with scissors or shave with a trimmer or razor all of the excess hair. You are left with the perfect hairline.", Image = "https://cdn.thisiswhyimbroke.com/images/hair-neckline-grooming-tool.jpg", Name = "Hairline Grooming Tool", Price = 14.95m, ProductCategory = 3, Quantity = 50, SKU = "naab004groomkit" },
                        new { ID = 5, Description = "Thinking of sending a Birthday, Congrats, Get Well Soon card? This is a quirky and hilarious alternative to the traditional card! Your friends, family, and others will get a kick out of it! ", Image = "https://cdn.thisiswhyimbroke.com/images/potato-parcel2-640x533.jpg", Name = "Custom Message Potato Parcel", Price = 9.99m, ProductCategory = 3, Quantity = 50, SKU = "naab005potato" },
                        new { ID = 6, Description = "You may not be made of money, but why can’t your suit be?", Image = "https://cdn.thisiswhyimbroke.com/images/cash-suit-640x533.jpg", Name = "Cash Suit", Price = 59.99m, ProductCategory = 1, Quantity = 50, SKU = "naab006cashsuit" },
                        new { ID = 7, Description = "Great for using a tablet as second (or third) Display for your laptop!", Image = "https://cdn.macrumors.com/article-new/2017/11/mountie1.jpg", Name = "Tablet Mounting Clip", Price = 34.95m, ProductCategory = 0, Quantity = 50, SKU = "naab007mountclip" },
                        new { ID = 8, Description = "Charge every single electronic device in your household simultaneously with the 49 port USB hub.", Image = "https://usb.brando.com/prod_img/zoom/UHUBS041500_3.jpg", Name = "49 Port USB Hub", Price = 165.00m, ProductCategory = 0, Quantity = 50, SKU = "naab008usbhub" },
                        new { ID = 9, Description = "Ensure Jr. thrives in today’s technology driven society by getting him started at a young age with the HTML for babies", Image = "https://i0.wp.com/www.daddycheckthisout.com/wp-content/uploads/2017/09/html-babies.jpg?fit=400%2C300", Name = "HTML For Babies", Price = 346.70m, ProductCategory = 3, Quantity = 50, SKU = "naab009forbabies" },
                        new { ID = 10, Description = "Get more done on your smartphone or tablet with help from the foldable keyboard.", Image = "https://images-na.ssl-images-amazon.com/images/G/01/aplusautomation/vendorimages/032cfa09-5986-4cbc-acd9-f2a2c68aac58.jpg._CB273765552__SL300__.jpg", Name = "Microsoft Foldable Keyboard", Price = 85.99m, ProductCategory = 0, Quantity = 50, SKU = "naab010msftkeyboard" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
